version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
    day: monday
  commit-message:
    prefix: docker
  labels:
  - docker
  - automated
  groups:
    docker_security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: ci
  labels:
  - ci
  - automated
  groups:
    minor-and-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    github-actions-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
