#!/bin/sh
MY-LOCATION=...
MY-DESTINATION=...
MY-SECOND-DESTINATION=...
SMB_NFS_SHARE=...
DISK=...

cd /local_shares/${MY-LOCATION}

duplicacy init -storage-name ${MY-LOCATION}-${MY-DESTINATION} ${MY-LOCATION}-${MY-DESTINATION} /unassigned_devices/${DISK}/${MY-LOCATION}
duplicacy add -bit-identical ${MY-LOCATION}-${MY-SECOND-DESTINATION} ${MY-LOCATION}-${MY-SECOND-DESTINATION} /smb_nfs_shares/${SMB_NFS_SHARE}/${MY-LOCATION}
duplicacy add ...

duplicacy list -storage ${MY-LOCATION}-${MY-DESTINATION}
duplicacy list -storage ${MY-LOCATION}-${MY-SECOND-DESTINATION}
duplicacy list ...